version: '2'
services:
  tc-cache:
    image: "redis:3.2.5"
    ports:
      - "6379:6379"
  elasticsearch14:
    image: itzg/elasticsearch:1.4
    ports:
       - '9200:9200'
       - '9300:9300'
    environment:
      CLUSTER: elasticsearch
      NODE_NAME: elasticsearch
  tc-informix:
    image: "appiriodevops/tc-database-scripts:73b37cb39abc55ba4456a3773b7c56b9aec2dacf"
    hostname: informix.cloud.topcoder.com
    container_name: iif_developer_edition
    environment: 
      LICENSE: accept
    ports:
      - "2021:2021"
      - "2022:2022"
      - "27017:27017"
      - "27018:27018"
      - "27883:27883"
    tty: true
  tc-direct-build:
    image: "appiriodevops/direct-app:build"
    volumes:
      - "${DIRECT_APP_SRC_ROOT}:/root/direct"
      - "${BUILT_DATA}:/data"
  tc-direct-with-volume:
    image: "appiriodevops/direct-app:run-volume"
    links:
      - "tc-informix"
      - "tc-cache"
    hostname: cockpit.cloud.topcoder.com
    volumes:
      - "${BUILT_JBOSS_DIR}:/root/jboss-4.2.3.GA"
    ports:
      - "443:443"
      - "8180:8180"
      - "1198:1198"
      - "1199:1199"
      - "3973:3973"
      - "5446:5446"
  tc-direct:
    image: "appiriodevops/direct-app:04680b3"
    links:
      - "tc-informix"
      - "tc-cache"
    hostname: cockpit.cloud.topcoder.com
    ports:
      - "443:443"
      - "8180:8180"
      - "1198:1198"
      - "1199:1199"
      - "3973:3973"
      - "5446:5446"
